version: '3'
services:
  notes:
    container_name: notes
    restart: always
    build: 
      context: ../
      dockerfile: dockerfile.notes
    ports:
      - 8080:8080
    labels:
      - otel.service.name=notes
      - otel.environment=dev
      - otel.version=0.0.1
    environment:
      DD_AGENT_HOST: otel-collector
      DD_DOGSTATSD_PORT: 8125
      DD_TRACE_AGENT_PORT: 8126
    depends_on:
      - calendar
      - otel-collector

  calendar:
    container_name: calendar
    restart: always
    build: 
      context: ../
      dockerfile: dockerfile.calendar
    ports:
      - 8081:8081
    labels:
       - otel.service.name=calendar
       - otel.environment=dev
       - otel.version=0.0.1
    environment:
      DD_AGENT_HOST: otel-collector
      DD_DOGSTATSD_PORT: 8125
      DD_TRACE_AGENT_PORT: 8126
    depends_on:
      - otel-collector
      
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 8125:8125/udp  # StatsD receiver 
      - 8126:8126  # Datadog receiver
      - 8889:8889  # Prometheus exporter
    depends_on:
      - jaeger

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - otel-collector

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686  # Jaeger UI
      - 4317:4317    # OTLP gRPC
      - 4318:4318    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true